2025-08-26 18:24:07,582 - INFO - Starting application...
2025-08-26 18:24:07,586 - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-08-26 18:24:07,587 - INFO - Socket connected: <socket.socket fd=836, family=23, type=1, proto=6, laddr=('::1', 55628, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:24:07,588 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D66C5382F0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D66C5382F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-08-26 18:24:07,592 - INFO - Aborting transport connection: state=1; <socket.socket fd=836, family=23, type=1, proto=6, laddr=('::1', 55628, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:24:07,592 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=836, family=23, type=1, proto=6, laddr=('::1', 55628, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:24:07,593 - INFO - Deactivating transport: state=1; <socket.socket fd=836, family=23, type=1, proto=6, laddr=('::1', 55628, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:24:07,593 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-08-26 18:24:07,593 - ERROR - Connection closed while authenticating indicating a probable authentication error
2025-08-26 18:24:07,593 - INFO - Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,593 - ERROR - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,594 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-08-26 18:24:07,594 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=836, family=23, type=1, proto=6, laddr=('::1', 55628, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:24:07,594 - INFO - Socket connected: <socket.socket fd=840, family=2, type=1, proto=6, laddr=('127.0.0.1', 55629), raddr=('127.0.0.1', 5672)>
2025-08-26 18:24:07,595 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D66C530A50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D66C530A50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-08-26 18:24:07,598 - INFO - Aborting transport connection: state=1; <socket.socket fd=840, family=2, type=1, proto=6, laddr=('127.0.0.1', 55629), raddr=('127.0.0.1', 5672)>
2025-08-26 18:24:07,598 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=840, family=2, type=1, proto=6, laddr=('127.0.0.1', 55629), raddr=('127.0.0.1', 5672)>
2025-08-26 18:24:07,598 - INFO - Deactivating transport: state=1; <socket.socket fd=840, family=2, type=1, proto=6, laddr=('127.0.0.1', 55629), raddr=('127.0.0.1', 5672)>
2025-08-26 18:24:07,599 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-08-26 18:24:07,599 - ERROR - Connection closed while authenticating indicating a probable authentication error
2025-08-26 18:24:07,599 - INFO - Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,599 - ERROR - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,599 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",).
2025-08-26 18:24:07,599 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,600 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=840, family=2, type=1, proto=6, laddr=('127.0.0.1', 55629), raddr=('127.0.0.1', 5672)>
2025-08-26 18:24:07,600 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-08-26 18:24:07,600 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "C:\Users\sunnyk_engineosol\PycharmProjects\data_crawler_framework\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-08-26 18:25:18,124 - INFO - Starting application...
2025-08-26 18:25:39,412 - INFO - Starting application...
2025-08-26 18:25:39,417 - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-08-26 18:25:39,418 - INFO - Socket connected: <socket.socket fd=520, family=23, type=1, proto=6, laddr=('::1', 55638, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:25:39,419 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000157737C82F0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000157737C82F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-08-26 18:25:39,470 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000157737C82F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:25:39,470 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000157737C82F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:25:39,471 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000157737C82F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:25:39,471 - INFO - Created channel=1
2025-08-26 18:25:39,477 - INFO - Getting proxy IP for current session
2025-08-26 18:25:40,774 - INFO - Proxy url dict created for request
2025-08-26 18:25:40,774 - INFO - proxy & headers set in request session
2025-08-26 18:25:40,775 - INFO - Setting up crawler to extract data
2025-08-26 18:25:43,953 - INFO - 1 - Home_Page: 200
2025-08-26 18:25:46,192 - INFO - 2 - Hotel_Page: 404
2025-08-26 18:25:46,193 - INFO - Referer URL: https://www.marriott.com/en-us/hotels/dpsbl/overview/
2025-08-26 18:25:46,194 - ERROR - Error Occured.
2025-08-26 18:25:46,194 - INFO - Closing application...
2025-08-26 18:25:46,201 - INFO - Getting proxy IP for current session
2025-08-26 18:25:47,452 - INFO - Proxy url dict created for request
2025-08-26 18:25:47,453 - INFO - proxy & headers set in request session
2025-08-26 18:25:47,454 - INFO - Setting up crawler to extract data
2025-08-26 18:25:50,050 - INFO - 1 - Home_Page: 200
2025-08-26 18:25:52,758 - INFO - 2 - Hotel_Page: 200
2025-08-26 18:25:52,759 - INFO - Referer URL: https://www.marriott.com/en-us/hotels/sellc-josun-palace-a-luxury-collection-hotel-seoul-gangnam/overview/
2025-08-26 18:25:53,727 - INFO - 3 - JS_Page: 200
2025-08-26 18:25:54,359 - INFO - 4 - Standard_Form_Page: 200
2025-08-26 18:25:57,382 - INFO - 5 - Submit_Form_Page: 200
2025-08-26 18:25:58,324 - INFO - 6 - Rate_List_Menu: 200
2025-08-26 18:25:58,867 - INFO - 7 - Next_JS_Page: 200
2025-08-26 18:25:59,620 - INFO - 8 - Book_Property_Page: 200
2025-08-26 18:26:00,502 - INFO - 9 - Standard_Rate_Page: 200
2025-08-26 18:26:01,821 - INFO - 10 - Promotional_Rate_Page: 200
2025-08-26 18:26:01,823 - ERROR - There are no redemption rates available for the dates you selected.
2025-08-26 18:26:01,823 - INFO - Closing application...
2025-08-26 18:26:01,834 - INFO - Getting proxy IP for current session
2025-08-26 18:26:03,670 - INFO - Proxy url dict created for request
2025-08-26 18:26:03,671 - INFO - proxy & headers set in request session
2025-08-26 18:26:03,672 - INFO - Setting up crawler to extract data
2025-08-26 18:26:15,493 - INFO - 1 - Home_Page: 200
2025-08-26 18:26:15,648 - ERROR - Exception occurred: HTTPSConnectionPool(host='www.marriott.com', port=443): Max retries exceeded with url: /en-us/hotels/sellc/overview/ (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2025-08-26 18:26:15,649 - INFO - Closing application...
2025-08-26 18:26:20,155 - ERROR - Exception occurred: HTTPSConnectionPool(host='www.marriott.com', port=443): Max retries exceeded with url: /default.mi (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2025-08-26 18:26:20,155 - INFO - Closing application...
2025-08-26 18:26:36,065 - INFO - 1 - Home_Page: 200
2025-08-26 18:26:36,237 - ERROR - Exception occurred: HTTPSConnectionPool(host='www.marriott.com', port=443): Max retries exceeded with url: /en-us/hotels/sellc/overview/ (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))
2025-08-26 18:26:36,237 - INFO - Closing application...
2025-08-26 18:26:36,243 - INFO - Getting proxy IP for current session
2025-08-26 18:26:46,978 - INFO - Getting proxy IP for current session
2025-08-26 18:26:48,243 - INFO - Proxy url dict created for request
2025-08-26 18:26:48,243 - INFO - proxy & headers set in request session
2025-08-26 18:26:48,244 - INFO - Setting up crawler to extract data
2025-08-26 18:26:58,606 - INFO - 1 - Home_Page: 200
2025-08-26 18:27:12,623 - INFO - 2 - Hotel_Page: 200
2025-08-26 18:27:12,624 - INFO - Referer URL: https://www.marriott.com/en-us/hotels/sellc-josun-palace-a-luxury-collection-hotel-seoul-gangnam/overview/
2025-08-26 18:27:18,900 - INFO - 3 - JS_Page: 200
2025-08-26 18:27:20,057 - INFO - 4 - Standard_Form_Page: 200
2025-08-26 18:27:26,186 - INFO - 5 - Submit_Form_Page: 200
2025-08-26 18:27:28,934 - INFO - 6 - Rate_List_Menu: 200
2025-08-26 18:27:30,127 - INFO - 7 - Next_JS_Page: 200
2025-08-26 18:27:31,471 - INFO - 8 - Book_Property_Page: 200
2025-08-26 18:27:33,451 - INFO - 9 - Standard_Rate_Page: 200
2025-08-26 18:27:36,587 - INFO - 10 - Promotional_Rate_Page: 200
2025-08-26 18:27:36,588 - ERROR - There are no redemption rates available for the dates you selected.
2025-08-26 18:27:36,589 - INFO - Closing application...
2025-08-26 18:27:36,597 - INFO - Getting proxy IP for current session
2025-08-26 18:29:22,175 - INFO - Starting application...
2025-08-26 18:29:22,180 - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-08-26 18:29:22,181 - INFO - Socket connected: <socket.socket fd=792, family=23, type=1, proto=6, laddr=('::1', 55670, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-08-26 18:29:22,182 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000019404A682F0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000019404A682F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-08-26 18:29:22,231 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000019404A682F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:29:22,232 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000019404A682F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:29:22,232 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000019404A682F0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-08-26 18:29:22,233 - INFO - Created channel=1
